# Generated by Django 4.2.20 on 2025-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("input_file", models.FileField(upload_to="uploads/")),
                ("output_file", models.FileField(upload_to="outputs/")),
                ("detection_type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "odapp_detectionhistory",
            },
        ),
        migrations.CreateModel(
            name="Signupdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=10)),
                ("ConfirmPassword", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "odapp_signupdb",
            },
        ),
    ]
